version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket cloudform-lambda-pipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
# phases:
#   install:
#     #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
#     #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
#     #runtime-versions:
#       # name: version
#       # name: version
#     commands:
#       - command:
#           - aws cloudformation package --template-file samTemplate.yaml --s3-bucket cloudform-lambda-pipeline --output-template-file outputSamTemplate.yaml
#       # - command
#   pre_build:
#     commands:
#       - npm install
#       # - command
#   build:
#     commands:
#       - npm run build
#       # - command
#   #post_build:
#     #commands:
#       # - command
#       # - command
# #reports:
#   #report-name-or-arn:
#     #files:
#       # - location
#       # - location
#     #base-directory: location
#     #discard-paths: yes
#     #file-format: JunitXml | CucumberJson
# artifacts:
#   files:
#     - '**/*'
#     # - location
#   #name: $(date +%Y-%m-%d)
#   #discard-paths: yes
#   #base-directory: location
# #cache:
#   #paths:
#     # - paths
