AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CD demo Lambda
Resources:
  GetActivityRight:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      # Role: 'arn:aws:iam::093833860903/MyLambdaRole'
      Events:
        HttpGet:
          GetActRightApi:
            Type: Api
            Properties:
              # ProtocolType: HTTP
              Path: /health
              Method: GET
      Environment:
        Variables:
          REGION: ap-south-1